using System.Diagnostics.CodeAnalysis;

namespace Tavstal.PayPalSDK.Constants;

/// <summary>
/// Represents a collection of predefined product category constants.
/// These constants are used to categorize products or services
/// in various applications, such as e-commerce or payment processing.
/// </summary>
[SuppressMessage("ReSharper", "InconsistentNaming")]
public class ProductCategories
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public const string AC_REFRIGERATION_REPAIR = "AC_REFRIGERATION_REPAIR";
    public const string ACADEMIC_SOFTWARE = "ACADEMIC_SOFTWARE";
    public const string ACCESSORIES = "ACCESSORIES";
    public const string ACCOUNTING = "ACCOUNTING";
    public const string ADULT = "ADULT";
    public const string ADVERTISING = "ADVERTISING";
    public const string AFFILIATED_AUTO_RENTAL = "AFFILIATED_AUTO_RENTAL";
    public const string AGENCIES = "AGENCIES";
    public const string AGGREGATORS = "AGGREGATORS";
    public const string AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER = "AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER";
    public const string AIR_CARRIERS_AIRLINES = "AIR_CARRIERS_AIRLINES";
    public const string AIRLINES = "AIRLINES";
    public const string AIRPORTS_FLYING_FIELDS = "AIRPORTS_FLYING_FIELDS";
    public const string ALCOHOLIC_BEVERAGES = "ALCOHOLIC_BEVERAGES";
    public const string AMUSEMENT_PARKS_CARNIVALS = "AMUSEMENT_PARKS_CARNIVALS";
    public const string ANIMATION = "ANIMATION";
    public const string ANTIQUES = "ANTIQUES";
    public const string APPLIANCES = "APPLIANCES";
    public const string AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS = "AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS";

    public const string ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES =
        "ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES";

    public const string ART_AND_CRAFT_SUPPLIES = "ART_AND_CRAFT_SUPPLIES";
    public const string ART_DEALERS_AND_GALLERIES = "ART_DEALERS_AND_GALLERIES";

    public const string ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS =
        "ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS";

    public const string ARTS_AND_CRAFTS = "ARTS_AND_CRAFTS";
    public const string ARTS_CRAFTS_AND_COLLECTIBLES = "ARTS_CRAFTS_AND_COLLECTIBLES";
    public const string AUDIO_BOOKS = "AUDIO_BOOKS";
    public const string AUTO_ASSOCIATIONS_CLUBS = "AUTO_ASSOCIATIONS_CLUBS";
    public const string AUTO_DEALER_USED_ONLY = "AUTO_DEALER_USED_ONLY";
    public const string AUTO_RENTALS = "AUTO_RENTALS";
    public const string AUTO_SERVICE = "AUTO_SERVICE";
    public const string AUTOMATED_FUEL_DISPENSERS = "AUTOMATED_FUEL_DISPENSERS";
    public const string AUTOMOBILE_ASSOCIATIONS = "AUTOMOBILE_ASSOCIATIONS";
    public const string AUTOMOTIVE = "AUTOMOTIVE";
    public const string AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER = "AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER";
    public const string AUTOMOTIVE_TOP_AND_BODY_SHOPS = "AUTOMOTIVE_TOP_AND_BODY_SHOPS";
    public const string AVIATION = "AVIATION";
    public const string BABIES_CLOTHING_AND_SUPPLIES = "BABIES_CLOTHING_AND_SUPPLIES";
    public const string BABY = "BABY";
    public const string BANDS_ORCHESTRAS_ENTERTAINERS = "BANDS_ORCHESTRAS_ENTERTAINERS";
    public const string BARBIES = "BARBIES";
    public const string BATH_AND_BODY = "BATH_AND_BODY";
    public const string BATTERIES = "BATTERIES";
    public const string BEAN_BABIES = "BEAN_BABIES";
    public const string BEAUTY = "BEAUTY";
    public const string BEAUTY_AND_FRAGRANCES = "BEAUTY_AND_FRAGRANCES";
    public const string BED_AND_BATH = "BED_AND_BATH";
    public const string BICYCLE_SHOPS_SALES_AND_SERVICE = "BICYCLE_SHOPS_SALES_AND_SERVICE";
    public const string BICYCLES_AND_ACCESSORIES = "BICYCLES_AND_ACCESSORIES";
    public const string BILLIARD_POOL_ESTABLISHMENTS = "BILLIARD_POOL_ESTABLISHMENTS";
    public const string BOAT_DEALERS = "BOAT_DEALERS";
    public const string BOAT_RENTALS_AND_LEASING = "BOAT_RENTALS_AND_LEASING";
    public const string BOATING_SAILING_AND_ACCESSORIES = "BOATING_SAILING_AND_ACCESSORIES";
    public const string BOOKS = "BOOKS";
    public const string BOOKS_AND_MAGAZINES = "BOOKS_AND_MAGAZINES";
    public const string BOOKS_MANUSCRIPTS = "BOOKS_MANUSCRIPTS";
    public const string BOOKS_PERIODICALS_AND_NEWSPAPERS = "BOOKS_PERIODICALS_AND_NEWSPAPERS";
    public const string BOWLING_ALLEYS = "BOWLING_ALLEYS";
    public const string BULLETIN_BOARD = "BULLETIN_BOARD";
    public const string BUS_LINE = "BUS_LINE";
    public const string BUS_LINES_CHARTERS_TOUR_BUSES = "BUS_LINES_CHARTERS_TOUR_BUSES";
    public const string BUSINESS = "BUSINESS";
    public const string BUSINESS_AND_SECRETARIAL_SCHOOLS = "BUSINESS_AND_SECRETARIAL_SCHOOLS";
    public const string BUYING_AND_SHOPPING_SERVICES_AND_CLUBS = "BUYING_AND_SHOPPING_SERVICES_AND_CLUBS";

    public const string CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES =
        "CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES";

    public const string CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO = "CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO";
    public const string CAMERA_AND_PHOTOGRAPHIC_SUPPLIES = "CAMERA_AND_PHOTOGRAPHIC_SUPPLIES";
    public const string CAMERAS = "CAMERAS";
    public const string CAMERAS_AND_PHOTOGRAPHY = "CAMERAS_AND_PHOTOGRAPHY";

    public const string CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS =
        "CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS";

    public const string CAMPING_AND_OUTDOORS = "CAMPING_AND_OUTDOORS";
    public const string CAMPING_AND_SURVIVAL = "CAMPING_AND_SURVIVAL";
    public const string CAR_AND_TRUCK_DEALERS = "CAR_AND_TRUCK_DEALERS";
    public const string CAR_AND_TRUCK_DEALERS_USED_ONLY = "CAR_AND_TRUCK_DEALERS_USED_ONLY";
    public const string CAR_AUDIO_AND_ELECTRONICS = "CAR_AUDIO_AND_ELECTRONICS";
    public const string CAR_RENTAL_AGENCY = "CAR_RENTAL_AGENCY";
    public const string CATALOG_MERCHANT = "CATALOG_MERCHANT";
    public const string CATALOG_RETAIL_MERCHANT = "CATALOG_RETAIL_MERCHANT";
    public const string CATERING_SERVICES = "CATERING_SERVICES";
    public const string CHARITY = "CHARITY";
    public const string CHECK_CASHIER = "CHECK_CASHIER";
    public const string CHILD_CARE_SERVICES = "CHILD_CARE_SERVICES";
    public const string CHILDREN_BOOKS = "CHILDREN_BOOKS";
    public const string CHIROPODISTS_PODIATRISTS = "CHIROPODISTS_PODIATRISTS";
    public const string CHIROPRACTORS = "CHIROPRACTORS";
    public const string CIGAR_STORES_AND_STANDS = "CIGAR_STORES_AND_STANDS";
    public const string CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS = "CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS";
    public const string CIVIL_SOCIAL_FRAT_ASSOCIATIONS = "CIVIL_SOCIAL_FRAT_ASSOCIATIONS";
    public const string CLOTHING = "CLOTHING";
    public const string CLOTHING_ACCESSORIES_AND_SHOES = "CLOTHING_ACCESSORIES_AND_SHOES";
    public const string CLOTHING_RENTAL = "CLOTHING_RENTAL";
    public const string COFFEE_AND_TEA = "COFFEE_AND_TEA";
    public const string COIN_OPERATED_BANKS_AND_CASINOS = "COIN_OPERATED_BANKS_AND_CASINOS";
    public const string COLLECTIBLES = "COLLECTIBLES";
    public const string COLLECTION_AGENCY = "COLLECTION_AGENCY";
    public const string COLLEGES_AND_UNIVERSITIES = "COLLEGES_AND_UNIVERSITIES";
    public const string COMMERCIAL_EQUIPMENT = "COMMERCIAL_EQUIPMENT";
    public const string COMMERCIAL_FOOTWEAR = "COMMERCIAL_FOOTWEAR";
    public const string COMMERCIAL_PHOTOGRAPHY = "COMMERCIAL_PHOTOGRAPHY";
    public const string COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS = "COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS";
    public const string COMMERCIAL_SPORTS_PROFESSIONA = "COMMERCIAL_SPORTS_PROFESSIONA";
    public const string COMMODITIES_AND_FUTURES_EXCHANGE = "COMMODITIES_AND_FUTURES_EXCHANGE";
    public const string COMPUTER_AND_DATA_PROCESSING_SERVICES = "COMPUTER_AND_DATA_PROCESSING_SERVICES";
    public const string COMPUTER_HARDWARE_AND_SOFTWARE = "COMPUTER_HARDWARE_AND_SOFTWARE";

    public const string COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS =
        "COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS";

    public const string CONSTRUCTION = "CONSTRUCTION";

    public const string CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED =
        "CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED";

    public const string CONSULTING_SERVICES = "CONSULTING_SERVICES";
    public const string CONSUMER_CREDIT_REPORTING_AGENCIES = "CONSUMER_CREDIT_REPORTING_AGENCIES";
    public const string CONVALESCENT_HOMES = "CONVALESCENT_HOMES";
    public const string COSMETIC_STORES = "COSMETIC_STORES";
    public const string COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL = "COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL";
    public const string COUNTERFEIT_CURRENCY_AND_STAMPS = "COUNTERFEIT_CURRENCY_AND_STAMPS";
    public const string COUNTERFEIT_ITEMS = "COUNTERFEIT_ITEMS";
    public const string COUNTRY_CLUBS = "COUNTRY_CLUBS";
    public const string COURIER_SERVICES = "COURIER_SERVICES";

    public const string COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS =
        "COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS";

    public const string COURT_COSTS_ALIMNY_CHILD_SUPT = "COURT_COSTS_ALIMNY_CHILD_SUPT";

    public const string COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW =
        "COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW";

    public const string CREDIT_CARDS = "CREDIT_CARDS";
    public const string CREDIT_UNION = "CREDIT_UNION";
    public const string CULTURE_AND_RELIGION = "CULTURE_AND_RELIGION";
    public const string DAIRY_PRODUCTS_STORES = "DAIRY_PRODUCTS_STORES";
    public const string DANCE_HALLS_STUDIOS_AND_SCHOOLS = "DANCE_HALLS_STUDIOS_AND_SCHOOLS";
    public const string DECORATIVE = "DECORATIVE";
    public const string DENTAL = "DENTAL";
    public const string DENTISTS_AND_ORTHODONTISTS = "DENTISTS_AND_ORTHODONTISTS";
    public const string DEPARTMENT_STORES = "DEPARTMENT_STORES";
    public const string DESKTOP_PCS = "DESKTOP_PCS";
    public const string DEVICES = "DEVICES";
    public const string DIECAST_TOYS_VEHICLES = "DIECAST_TOYS_VEHICLES";
    public const string DIGITAL_GAMES = "DIGITAL_GAMES";
    public const string DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC = "DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC";
    public const string DIRECT_MARKETING = "DIRECT_MARKETING";
    public const string DIRECT_MARKETING_CATALOG_MERCHANT = "DIRECT_MARKETING_CATALOG_MERCHANT";
    public const string DIRECT_MARKETING_INBOUND_TELE = "DIRECT_MARKETING_INBOUND_TELE";
    public const string DIRECT_MARKETING_OUTBOUND_TELE = "DIRECT_MARKETING_OUTBOUND_TELE";
    public const string DIRECT_MARKETING_SUBSCRIPTION = "DIRECT_MARKETING_SUBSCRIPTION";
    public const string DISCOUNT_STORES = "DISCOUNT_STORES";
    public const string DOOR_TO_DOOR_SALES = "DOOR_TO_DOOR_SALES";
    public const string DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY = "DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY";
    public const string DRINKING_PLACES = "DRINKING_PLACES";
    public const string DRUGSTORE = "DRUGSTORE";
    public const string DURABLE_GOODS = "DURABLE_GOODS";
    public const string ECOMMERCE_DEVELOPMENT = "ECOMMERCE_DEVELOPMENT";
    public const string ECOMMERCE_SERVICES = "ECOMMERCE_SERVICES";
    public const string EDUCATIONAL_AND_TEXTBOOKS = "EDUCATIONAL_AND_TEXTBOOKS";
    public const string ELECTRIC_RAZOR_STORES = "ELECTRIC_RAZOR_STORES";
    public const string ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR = "ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR";
    public const string ELECTRICAL_CONTRACTORS = "ELECTRICAL_CONTRACTORS";
    public const string ELECTRICAL_PARTS_AND_EQUIPMENT = "ELECTRICAL_PARTS_AND_EQUIPMENT";
    public const string ELECTRONIC_CASH = "ELECTRONIC_CASH";
    public const string ELEMENTARY_AND_SECONDARY_SCHOOLS = "ELEMENTARY_AND_SECONDARY_SCHOOLS";
    public const string EMPLOYMENT = "EMPLOYMENT";
    public const string ENTERTAINERS = "ENTERTAINERS";
    public const string ENTERTAINMENT_AND_MEDIA = "ENTERTAINMENT_AND_MEDIA";

    public const string EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING =
        "EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING";

    public const string ESCROW = "ESCROW";
    public const string EVENT_AND_WEDDING_PLANNING = "EVENT_AND_WEDDING_PLANNING";
    public const string EXERCISE_AND_FITNESS = "EXERCISE_AND_FITNESS";
    public const string EXERCISE_EQUIPMENT = "EXERCISE_EQUIPMENT";
    public const string EXTERMINATING_AND_DISINFECTING_SERVICES = "EXTERMINATING_AND_DISINFECTING_SERVICES";
    public const string FABRICS_AND_SEWING = "FABRICS_AND_SEWING";
    public const string FAMILY_CLOTHING_STORES = "FAMILY_CLOTHING_STORES";
    public const string FASHION_JEWELRY = "FASHION_JEWELRY";
    public const string FAST_FOOD_RESTAURANTS = "FAST_FOOD_RESTAURANTS";
    public const string FICTION_AND_NONFICTION = "FICTION_AND_NONFICTION";
    public const string FINANCE_COMPANY = "FINANCE_COMPANY";
    public const string FINANCIAL_AND_INVESTMENT_ADVICE = "FINANCIAL_AND_INVESTMENT_ADVICE";

    public const string FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES =
        "FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES";

    public const string FIREARM_ACCESSORIES = "FIREARM_ACCESSORIES";
    public const string FIREARMS_WEAPONS_AND_KNIVES = "FIREARMS_WEAPONS_AND_KNIVES";
    public const string FIREPLACE_AND_FIREPLACE_SCREENS = "FIREPLACE_AND_FIREPLACE_SCREENS";
    public const string FIREWORKS = "FIREWORKS";
    public const string FISHING = "FISHING";
    public const string FLORISTS = "FLORISTS";
    public const string FLOWERS = "FLOWERS";
    public const string FOOD_DRINK_AND_NUTRITION = "FOOD_DRINK_AND_NUTRITION";
    public const string FOOD_PRODUCTS = "FOOD_PRODUCTS";
    public const string FOOD_RETAIL_AND_SERVICE = "FOOD_RETAIL_AND_SERVICE";
    public const string FRAGRANCES_AND_PERFUMES = "FRAGRANCES_AND_PERFUMES";
    public const string FREEZER_AND_LOCKER_MEAT_PROVISIONERS = "FREEZER_AND_LOCKER_MEAT_PROVISIONERS";
    public const string FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL = "FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL";
    public const string FUEL_DEALERS_NON_AUTOMOTIVE = "FUEL_DEALERS_NON_AUTOMOTIVE";
    public const string FUNERAL_SERVICES_AND_CREMATORIES = "FUNERAL_SERVICES_AND_CREMATORIES";
    public const string FURNISHING_AND_DECORATING = "FURNISHING_AND_DECORATING";
    public const string FURNITURE = "FURNITURE";
    public const string FURRIERS_AND_FUR_SHOPS = "FURRIERS_AND_FUR_SHOPS";
    public const string GADGETS_AND_OTHER_ELECTRONICS = "GADGETS_AND_OTHER_ELECTRONICS";
    public const string GAMBLING = "GAMBLING";
    public const string GAME_SOFTWARE = "GAME_SOFTWARE";
    public const string GAMES = "GAMES";
    public const string GARDEN_SUPPLIES = "GARDEN_SUPPLIES";
    public const string GENERAL = "GENERAL";
    public const string GENERAL_CONTRACTORS = "GENERAL_CONTRACTORS";
    public const string GENERAL_GOVERNMENT = "GENERAL_GOVERNMENT";
    public const string GENERAL_SOFTWARE = "GENERAL_SOFTWARE";
    public const string GENERAL_TELECOM = "GENERAL_TELECOM";
    public const string GIFTS_AND_FLOWERS = "GIFTS_AND_FLOWERS";
    public const string GLASS_PAINT_AND_WALLPAPER_STORES = "GLASS_PAINT_AND_WALLPAPER_STORES";
    public const string GLASSWARE_CRYSTAL_STORES = "GLASSWARE_CRYSTAL_STORES";
    public const string GOVERNMENT = "GOVERNMENT";
    public const string GOVERNMENT_IDS_AND_LICENSES = "GOVERNMENT_IDS_AND_LICENSES";

    public const string GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING =
        "GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING";

    public const string GOVERNMENT_OWNED_LOTTERIES = "GOVERNMENT_OWNED_LOTTERIES";
    public const string GOVERNMENT_SERVICES = "GOVERNMENT_SERVICES";
    public const string GRAPHIC_AND_COMMERCIAL_DESIGN = "GRAPHIC_AND_COMMERCIAL_DESIGN";
    public const string GREETING_CARDS = "GREETING_CARDS";
    public const string GROCERY_STORES_AND_SUPERMARKETS = "GROCERY_STORES_AND_SUPERMARKETS";
    public const string HARDWARE_AND_TOOLS = "HARDWARE_AND_TOOLS";
    public const string HARDWARE_EQUIPMENT_AND_SUPPLIES = "HARDWARE_EQUIPMENT_AND_SUPPLIES";
    public const string HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS = "HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS";
    public const string HEALTH_AND_BEAUTY_SPAS = "HEALTH_AND_BEAUTY_SPAS";
    public const string HEALTH_AND_NUTRITION = "HEALTH_AND_NUTRITION";
    public const string HEALTH_AND_PERSONAL_CARE = "HEALTH_AND_PERSONAL_CARE";
    public const string HEARING_AIDS_SALES_AND_SUPPLIES = "HEARING_AIDS_SALES_AND_SUPPLIES";
    public const string HEATING_PLUMBING_AC = "HEATING_PLUMBING_AC";
    public const string HIGH_RISK_MERCHANT = "HIGH_RISK_MERCHANT";
    public const string HIRING_SERVICES = "HIRING_SERVICES";
    public const string HOBBIES_TOYS_AND_GAMES = "HOBBIES_TOYS_AND_GAMES";
    public const string HOME_AND_GARDEN = "HOME_AND_GARDEN";
    public const string HOME_AUDIO = "HOME_AUDIO";
    public const string HOME_DECOR = "HOME_DECOR";
    public const string HOME_ELECTRONICS = "HOME_ELECTRONICS";
    public const string HOSPITALS = "HOSPITALS";
    public const string HOTELS_MOTELS_INNS_RESORTS = "HOTELS_MOTELS_INNS_RESORTS";
    public const string HOUSEWARES = "HOUSEWARES";
    public const string HUMAN_PARTS_AND_REMAINS = "HUMAN_PARTS_AND_REMAINS";
    public const string HUMOROUS_GIFTS_AND_NOVELTIES = "HUMOROUS_GIFTS_AND_NOVELTIES";
    public const string HUNTING = "HUNTING";
    public const string IDS_LICENSES_AND_PASSPORTS = "IDS_LICENSES_AND_PASSPORTS";
    public const string ILLEGAL_DRUGS_AND_PARAPHERNALIA = "ILLEGAL_DRUGS_AND_PARAPHERNALIA";
    public const string INDUSTRIAL = "INDUSTRIAL";
    public const string INDUSTRIAL_AND_MANUFACTURING_SUPPLIES = "INDUSTRIAL_AND_MANUFACTURING_SUPPLIES";
    public const string INSURANCE_AUTO_AND_HOME = "INSURANCE_AUTO_AND_HOME";
    public const string INSURANCE_DIRECT = "INSURANCE_DIRECT";
    public const string INSURANCE_LIFE_AND_ANNUITY = "INSURANCE_LIFE_AND_ANNUITY";
    public const string INSURANCE_SALES_UNDERWRITING = "INSURANCE_SALES_UNDERWRITING";
    public const string INSURANCE_UNDERWRITING_PREMIUMS = "INSURANCE_UNDERWRITING_PREMIUMS";
    public const string INTERNET_AND_NETWORK_SERVICES = "INTERNET_AND_NETWORK_SERVICES";
    public const string INTRA_COMPANY_PURCHASES = "INTRA_COMPANY_PURCHASES";
    public const string LABORATORIES_DENTAL_MEDICAL = "LABORATORIES_DENTAL_MEDICAL";
    public const string LANDSCAPING = "LANDSCAPING";
    public const string LANDSCAPING_AND_HORTICULTURAL_SERVICES = "LANDSCAPING_AND_HORTICULTURAL_SERVICES";
    public const string LAUNDRY_CLEANING_SERVICES = "LAUNDRY_CLEANING_SERVICES";
    public const string LEGAL = "LEGAL";
    public const string LEGAL_SERVICES_AND_ATTORNEYS = "LEGAL_SERVICES_AND_ATTORNEYS";
    public const string LOCAL_DELIVERY_SERVICE = "LOCAL_DELIVERY_SERVICE";
    public const string LOCKSMITH = "LOCKSMITH";
    public const string LODGING_AND_ACCOMMODATIONS = "LODGING_AND_ACCOMMODATIONS";
    public const string LOTTERY_AND_CONTESTS = "LOTTERY_AND_CONTESTS";
    public const string LUGGAGE_AND_LEATHER_GOODS = "LUGGAGE_AND_LEATHER_GOODS";
    public const string LUMBER_AND_BUILDING_MATERIALS = "LUMBER_AND_BUILDING_MATERIALS";
    public const string MAGAZINES = "MAGAZINES";
    public const string MAINTENANCE_AND_REPAIR_SERVICES = "MAINTENANCE_AND_REPAIR_SERVICES";
    public const string MAKEUP_AND_COSMETICS = "MAKEUP_AND_COSMETICS";
    public const string MANUAL_CASH_DISBURSEMENTS = "MANUAL_CASH_DISBURSEMENTS";
    public const string MASSAGE_PARLORS = "MASSAGE_PARLORS";
    public const string MEDICAL = "MEDICAL";
    public const string MEDICAL_AND_PHARMACEUTICAL = "MEDICAL_AND_PHARMACEUTICAL";
    public const string MEDICAL_CARE = "MEDICAL_CARE";
    public const string MEDICAL_EQUIPMENT_AND_SUPPLIES = "MEDICAL_EQUIPMENT_AND_SUPPLIES";
    public const string MEDICAL_SERVICES = "MEDICAL_SERVICES";
    public const string MEETING_PLANNERS = "MEETING_PLANNERS";
    public const string MEMBERSHIP_CLUBS_AND_ORGANIZATIONS = "MEMBERSHIP_CLUBS_AND_ORGANIZATIONS";
    public const string MEMBERSHIP_COUNTRY_CLUBS_GOLF = "MEMBERSHIP_COUNTRY_CLUBS_GOLF";
    public const string MEMORABILIA = "MEMORABILIA";
    public const string MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES = "MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES";
    public const string MEN_CLOTHING = "MEN_CLOTHING";
    public const string MERCHANDISE = "MERCHANDISE";
    public const string METAPHYSICAL = "METAPHYSICAL";
    public const string MILITARIA = "MILITARIA";
    public const string MILITARY_AND_CIVIL_SERVICE_UNIFORMS = "MILITARY_AND_CIVIL_SERVICE_UNIFORMS";

    public const string MISC_AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS =
        "MISC._AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS";

    public const string MISC_GENERAL_MERCHANDISE = "MISC._GENERAL_MERCHANDISE";
    public const string MISCELLANEOUS_GENERAL_SERVICES = "MISCELLANEOUS_GENERAL_SERVICES";

    public const string MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES =
        "MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES";

    public const string MODEL_KITS = "MODEL_KITS";
    public const string MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION = "MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION";
    public const string MONEY_TRANSFER_MERCHANT = "MONEY_TRANSFER_MERCHANT";
    public const string MOTION_PICTURE_THEATERS = "MOTION_PICTURE_THEATERS";
    public const string MOTOR_FREIGHT_CARRIERS_AND_TRUCKING = "MOTOR_FREIGHT_CARRIERS_AND_TRUCKING";
    public const string MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL = "MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL";
    public const string MOTOR_HOMES_DEALERS = "MOTOR_HOMES_DEALERS";
    public const string MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS = "MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS";
    public const string MOTORCYCLE_DEALERS = "MOTORCYCLE_DEALERS";
    public const string MOTORCYCLES = "MOTORCYCLES";
    public const string MOVIE = "MOVIE";
    public const string MOVIE_TICKETS = "MOVIE_TICKETS";
    public const string MOVING_AND_STORAGE = "MOVING_AND_STORAGE";
    public const string MULTI_LEVEL_MARKETING = "MULTI_LEVEL_MARKETING";
    public const string MUSIC_CDS_CASSETTES_AND_ALBUMS = "MUSIC_CDS_CASSETTES_AND_ALBUMS";
    public const string MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC = "MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC";
    public const string NETWORKING = "NETWORKING";
    public const string NEW_AGE = "NEW_AGE";
    public const string NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE = "NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE";
    public const string NEWS_DEALERS_AND_NEWSTANDS = "NEWS_DEALERS_AND_NEWSTANDS";
    public const string NON_DURABLE_GOODS = "NON_DURABLE_GOODS";
    public const string NON_FICTION = "NON_FICTION";
    public const string NON_PROFIT_POLITICAL_AND_RELIGION = "NON_PROFIT_POLITICAL_AND_RELIGION";
    public const string NONPROFIT = "NONPROFIT";
    public const string NOVELTIES = "NOVELTIES";
    public const string OEM_SOFTWARE = "OEM_SOFTWARE";
    public const string OFFICE_SUPPLIES_AND_EQUIPMENT = "OFFICE_SUPPLIES_AND_EQUIPMENT";
    public const string ONLINE_DATING = "ONLINE_DATING";
    public const string ONLINE_GAMING = "ONLINE_GAMING";
    public const string ONLINE_GAMING_CURRENCY = "ONLINE_GAMING_CURRENCY";
    public const string ONLINE_SERVICES = "ONLINE_SERVICES";
    public const string OOUTBOUND_TELEMARKETING_MERCH = "OOUTBOUND_TELEMARKETING_MERCH";
    public const string OPHTHALMOLOGISTS_OPTOMETRIST = "OPHTHALMOLOGISTS_OPTOMETRIST";
    public const string OPTICIANS_AND_DISPENSING = "OPTICIANS_AND_DISPENSING";
    public const string ORTHOPEDIC_GOODS_PROSTHETICS = "ORTHOPEDIC_GOODS_PROSTHETICS";
    public const string OSTEOPATHS = "OSTEOPATHS";
    public const string OTHER = "OTHER";
    public const string PACKAGE_TOUR_OPERATORS = "PACKAGE_TOUR_OPERATORS";
    public const string PAINTBALL = "PAINTBALL";
    public const string PAINTS_VARNISHES_AND_SUPPLIES = "PAINTS_VARNISHES_AND_SUPPLIES";
    public const string PARKING_LOTS_AND_GARAGES = "PARKING_LOTS_AND_GARAGES";
    public const string PARTS_AND_ACCESSORIES = "PARTS_AND_ACCESSORIES";
    public const string PAWN_SHOPS = "PAWN_SHOPS";
    public const string PAYCHECK_LENDER_OR_CASH_ADVANCE = "PAYCHECK_LENDER_OR_CASH_ADVANCE";
    public const string PERIPHERALS = "PERIPHERALS";
    public const string PERSONALIZED_GIFTS = "PERSONALIZED_GIFTS";
    public const string PET_SHOPS_PET_FOOD_AND_SUPPLIES = "PET_SHOPS_PET_FOOD_AND_SUPPLIES";
    public const string PETROLEUM_AND_PETROLEUM_PRODUCTS = "PETROLEUM_AND_PETROLEUM_PRODUCTS";
    public const string PETS_AND_ANIMALS = "PETS_AND_ANIMALS";
    public const string PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING = "PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING";
    public const string PHOTOGRAPHIC_STUDIOS_PORTRAITS = "PHOTOGRAPHIC_STUDIOS_PORTRAITS";
    public const string PHOTOGRAPHY = "PHOTOGRAPHY";
    public const string PHYSICAL_GOOD = "PHYSICAL_GOOD";
    public const string PICTURE_VIDEO_PRODUCTION = "PICTURE_VIDEO_PRODUCTION";
    public const string PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS = "PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS";
    public const string PLANTS_AND_SEEDS = "PLANTS_AND_SEEDS";
    public const string PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES = "PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES";
    public const string POLICE_RELATED_ITEMS = "POLICE_RELATED_ITEMS";
    public const string POLITICAL_ORGANIZATIONS = "POLITICAL_ORGANIZATIONS";
    public const string POSTAL_SERVICES_GOVERNMENT_ONLY = "POSTAL_SERVICES_GOVERNMENT_ONLY";
    public const string POSTERS = "POSTERS";
    public const string PREPAID_AND_STORED_VALUE_CARDS = "PREPAID_AND_STORED_VALUE_CARDS";
    public const string PRESCRIPTION_DRUGS = "PRESCRIPTION_DRUGS";
    public const string PROMOTIONAL_ITEMS = "PROMOTIONAL_ITEMS";
    public const string PUBLIC_WAREHOUSING_AND_STORAGE = "PUBLIC_WAREHOUSING_AND_STORAGE";
    public const string PUBLISHING_AND_PRINTING = "PUBLISHING_AND_PRINTING";
    public const string PUBLISHING_SERVICES = "PUBLISHING_SERVICES";
    public const string RADAR_DECTORS = "RADAR_DECTORS";
    public const string RADIO_TELEVISION_AND_STEREO_REPAIR = "RADIO_TELEVISION_AND_STEREO_REPAIR";
    public const string REAL_ESTATE = "REAL_ESTATE";
    public const string REAL_ESTATE_AGENT = "REAL_ESTATE_AGENT";
    public const string REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS = "REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS";
    public const string RELIGION_AND_SPIRITUALITY_FOR_PROFIT = "RELIGION_AND_SPIRITUALITY_FOR_PROFIT";
    public const string RELIGIOUS = "RELIGIOUS";
    public const string RELIGIOUS_ORGANIZATIONS = "RELIGIOUS_ORGANIZATIONS";
    public const string REMITTANCE = "REMITTANCE";
    public const string RENTAL_PROPERTY_MANAGEMENT = "RENTAL_PROPERTY_MANAGEMENT";
    public const string RESIDENTIAL = "RESIDENTIAL";
    public const string RETAIL = "RETAIL";
    public const string RETAIL_FINE_JEWELRY_AND_WATCHES = "RETAIL_FINE_JEWELRY_AND_WATCHES";
    public const string REUPHOLSTERY_AND_FURNITURE_REPAIR = "REUPHOLSTERY_AND_FURNITURE_REPAIR";
    public const string RINGS = "RINGS";
    public const string ROOFING_SIDING_SHEET_METAL = "ROOFING_SIDING_SHEET_METAL";
    public const string RUGS_AND_CARPETS = "RUGS_AND_CARPETS";
    public const string SCHOOLS_AND_COLLEGES = "SCHOOLS_AND_COLLEGES";
    public const string SCIENCE_FICTION = "SCIENCE_FICTION";
    public const string SCRAPBOOKING = "SCRAPBOOKING";
    public const string SCULPTURES = "SCULPTURES";
    public const string SECURITIES_BROKERS_AND_DEALERS = "SECURITIES_BROKERS_AND_DEALERS";
    public const string SECURITY_AND_SURVEILLANCE = "SECURITY_AND_SURVEILLANCE";
    public const string SECURITY_AND_SURVEILLANCE_EQUIPMENT = "SECURITY_AND_SURVEILLANCE_EQUIPMENT";
    public const string SECURITY_BROKERS_AND_DEALERS = "SECURITY_BROKERS_AND_DEALERS";
    public const string SEMINARS = "SEMINARS";
    public const string SERVICE_STATIONS = "SERVICE_STATIONS";
    public const string SERVICES = "SERVICES";

    public const string SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES =
        "SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES";

    public const string SHIPPING_AND_PACKING = "SHIPPING_AND_PACKING";
    public const string SHOE_REPAIR_HAT_CLEANING = "SHOE_REPAIR_HAT_CLEANING";
    public const string SHOE_STORES = "SHOE_STORES";
    public const string SHOES = "SHOES";
    public const string SNOWMOBILE_DEALERS = "SNOWMOBILE_DEALERS";
    public const string SOFTWARE = "SOFTWARE";
    public const string SPECIALTY_AND_MISC_FOOD_STORES = "SPECIALTY_AND_MISC._FOOD_STORES";

    public const string SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS =
        "SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS";

    public const string SPECIALTY_OR_RARE_PETS = "SPECIALTY_OR_RARE_PETS";
    public const string SPORT_GAMES_AND_TOYS = "SPORT_GAMES_AND_TOYS";
    public const string SPORTING_AND_RECREATIONAL_CAMPS = "SPORTING_AND_RECREATIONAL_CAMPS";
    public const string SPORTING_GOODS = "SPORTING_GOODS";
    public const string SPORTS_AND_OUTDOORS = "SPORTS_AND_OUTDOORS";
    public const string SPORTS_AND_RECREATION = "SPORTS_AND_RECREATION";
    public const string STAMP_AND_COIN = "STAMP_AND_COIN";
    public const string STATIONARY_PRINTING_AND_WRITING_PAPER = "STATIONARY_PRINTING_AND_WRITING_PAPER";
    public const string STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES = "STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES";

    public const string STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES =
        "STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES";

    public const string STORED_VALUE_CARDS = "STORED_VALUE_CARDS";
    public const string SUPPLIES = "SUPPLIES";
    public const string SUPPLIES_AND_TOYS = "SUPPLIES_AND_TOYS";
    public const string SURVEILLANCE_EQUIPMENT = "SURVEILLANCE_EQUIPMENT";
    public const string SWIMMING_POOLS_AND_SPAS = "SWIMMING_POOLS_AND_SPAS";
    public const string SWIMMING_POOLS_SALES_SUPPLIES_SERVICES = "SWIMMING_POOLS_SALES_SUPPLIES_SERVICES";
    public const string TAILORS_AND_ALTERATIONS = "TAILORS_AND_ALTERATIONS";
    public const string TAX_PAYMENTS = "TAX_PAYMENTS";
    public const string TAX_PAYMENTS_GOVERNMENT_AGENCIES = "TAX_PAYMENTS_GOVERNMENT_AGENCIES";
    public const string TAXICABS_AND_LIMOUSINES = "TAXICABS_AND_LIMOUSINES";
    public const string TELECOMMUNICATION_SERVICES = "TELECOMMUNICATION_SERVICES";
    public const string TELEPHONE_CARDS = "TELEPHONE_CARDS";
    public const string TELEPHONE_EQUIPMENT = "TELEPHONE_EQUIPMENT";
    public const string TELEPHONE_SERVICES = "TELEPHONE_SERVICES";
    public const string THEATER = "THEATER";
    public const string TIRE_RETREADING_AND_REPAIR = "TIRE_RETREADING_AND_REPAIR";
    public const string TOLL_OR_BRIDGE_FEES = "TOLL_OR_BRIDGE_FEES";
    public const string TOOLS_AND_EQUIPMENT = "TOOLS_AND_EQUIPMENT";
    public const string TOURIST_ATTRACTIONS_AND_EXHIBITS = "TOURIST_ATTRACTIONS_AND_EXHIBITS";
    public const string TOWING_SERVICE = "TOWING_SERVICE";
    public const string TOYS_AND_GAMES = "TOYS_AND_GAMES";
    public const string TRADE_AND_VOCATIONAL_SCHOOLS = "TRADE_AND_VOCATIONAL_SCHOOLS";
    public const string TRADEMARK_INFRINGEMENT = "TRADEMARK_INFRINGEMENT";
    public const string TRAILER_PARKS_AND_CAMPGROUNDS = "TRAILER_PARKS_AND_CAMPGROUNDS";
    public const string TRAINING_SERVICES = "TRAINING_SERVICES";
    public const string TRANSPORTATION_SERVICES = "TRANSPORTATION_SERVICES";
    public const string TRAVEL = "TRAVEL";
    public const string TRUCK_AND_UTILITY_TRAILER_RENTALS = "TRUCK_AND_UTILITY_TRAILER_RENTALS";
    public const string TRUCK_STOP = "TRUCK_STOP";
    public const string TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES = "TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES";
    public const string USED_MERCHANDISE_AND_SECONDHAND_STORES = "USED_MERCHANDISE_AND_SECONDHAND_STORES";
    public const string USED_PARTS_MOTOR_VEHICLE = "USED_PARTS_MOTOR_VEHICLE";
    public const string UTILITIES = "UTILITIES";
    public const string UTILITIES_ELECTRIC_GAS_WATER_SANITARY = "UTILITIES_ELECTRIC_GAS_WATER_SANITARY";
    public const string VARIETY_STORES = "VARIETY_STORES";
    public const string VEHICLE_SALES = "VEHICLE_SALES";
    public const string VEHICLE_SERVICE_AND_ACCESSORIES = "VEHICLE_SERVICE_AND_ACCESSORIES";
    public const string VIDEO_EQUIPMENT = "VIDEO_EQUIPMENT";
    public const string VIDEO_GAME_ARCADES_ESTABLISH = "VIDEO_GAME_ARCADES_ESTABLISH";
    public const string VIDEO_GAMES_AND_SYSTEMS = "VIDEO_GAMES_AND_SYSTEMS";
    public const string VIDEO_TAPE_RENTAL_STORES = "VIDEO_TAPE_RENTAL_STORES";
    public const string VINTAGE_AND_COLLECTIBLE_VEHICLES = "VINTAGE_AND_COLLECTIBLE_VEHICLES";
    public const string VINTAGE_AND_COLLECTIBLES = "VINTAGE_AND_COLLECTIBLES";
    public const string VITAMINS_AND_SUPPLEMENTS = "VITAMINS_AND_SUPPLEMENTS";
    public const string VOCATIONAL_AND_TRADE_SCHOOLS = "VOCATIONAL_AND_TRADE_SCHOOLS";
    public const string WATCH_CLOCK_AND_JEWELRY_REPAIR = "WATCH_CLOCK_AND_JEWELRY_REPAIR";
    public const string WEB_HOSTING_AND_DESIGN = "WEB_HOSTING_AND_DESIGN";
    public const string WELDING_REPAIR = "WELDING_REPAIR";
    public const string WHOLESALE_CLUBS = "WHOLESALE_CLUBS";
    public const string WHOLESALE_FLORIST_SUPPLIERS = "WHOLESALE_FLORIST_SUPPLIERS";
    public const string WHOLESALE_PRESCRIPTION_DRUGS = "WHOLESALE_PRESCRIPTION_DRUGS";
    public const string WILDLIFE_PRODUCTS = "WILDLIFE_PRODUCTS";
    public const string WIRE_TRANSFER = "WIRE_TRANSFER";
    public const string WIRE_TRANSFER_AND_MONEY_ORDER = "WIRE_TRANSFER_AND_MONEY_ORDER";
    public const string WOMEN_ACCESSORY_SPECIALITY = "WOMEN_ACCESSORY_SPECIALITY";
    public const string WOMEN_CLOTHING = "WOMEN_CLOTHING";
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
